# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
shape = (7,7,)
random_tensor1 = torch.rand(shape)
print(f"Random Tensor.:\n{random_tensor1}\n")

Random Tensor.:
tensor([[0.6370, 0.9682, 0.2717, 0.3362, 0.3219, 0.4463, 0.2355],
        [0.6045, 0.9688, 0.0248, 0.9609, 0.9093, 0.9644, 0.9372],
        [0.9734, 0.6503, 0.4180, 0.3417, 0.0466, 0.1815, 0.1084],
        [0.9854, 0.1347, 0.5361, 0.2860, 0.8678, 0.6476, 0.9734],
        [0.4484, 0.1659, 0.4393, 0.7987, 0.6060, 0.1231, 0.7797],
        [0.5839, 0.0685, 0.1384, 0.9499, 0.1899, 0.5742, 0.2650],
        [0.2967, 0.9188, 0.0138, 0.9556, 0.6250, 0.3735, 0.1683]])



### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
shape = (1,7,)
random_tensor2 = torch.rand(shape)
random_tensor3 = random_tensor2.transpose(0, 1)  # Swaps 2nd and 3rd dimension
random_tensor3
# Perform matrix multiplication 
#print(torch.matmul(random_tensor1, random_tensor2))

tensor([[0.7423],
        [0.8253],
        [0.5581],
        [0.1071],
        [0.1663],
        [0.1499],
        [0.5151]])

In [4]:
print(torch.matmul(random_tensor1, random_tensor3))

tensor([[1.7013],
        [2.1436],
        [1.6200],
        [1.9152],
        [1.3214],
        [0.9230],
        [1.3352]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0) 
# Create two random tensors
shape = (7,7,)
random_tensor1 = torch.rand(shape)

shape = (1,7,)
random_tensor2 = torch.rand(shape)
random_tensor3 = random_tensor2.transpose(0, 1)

# Matrix multiply tensors
print(torch.matmul(random_tensor1, random_tensor3))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
# Check for access to GPU
# Create two random tensors on GPU
shape = (2,3,)
random_tensor1 = torch.rand(shape)

shape = (2,3,)
random_tensor2 = torch.rand(shape)
random_tensor3 = random_tensor2.transpose(0, 1)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
print(torch.matmul(random_tensor1, random_tensor3))

tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]])


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
print(torch.max(torch.matmul(random_tensor1, random_tensor3)))
# Find min
print(torch.min(torch.matmul(random_tensor1, random_tensor3)))

tensor(1.0651)
tensor(0.3129)


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
tensor = torch.matmul(random_tensor1, random_tensor3)

flat_max_idx = torch.argmax(tensor)
flat_min_idx = torch.argmin(tensor)

max_index = torch.unravel_index(flat_max_idx, tensor.shape)
min_index = torch.unravel_index(flat_min_idx, tensor.shape)

# Find arg max
print("Max index:", max_index)
# Find arg min
print("Min index:", min_index)

Max index: (tensor(1), tensor(0))
Min index: (tensor(0), tensor(0))



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
shape = (1, 1, 1, 10,)
random_tensor1 = torch.rand(shape)
print(random_tensor1)
print(random_tensor1.shape)

# Remove single dimensions
random_tensor2 = torch.squeeze(random_tensor1)

# Print out tensors and their shapes
print(random_tensor2)
print(random_tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
